server:
  port: 8080

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5435/notificationdb
    username: notificationuser
    password: notificationpass
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.orderplatform.*"
        spring.json.use.type.headers: false

kafka:
  topic:
    order-events: order-events
    payment-events: payment-events
    inventory-events: inventory-events

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.orderplatform: DEBUG
    org.apache.kafka: WARN
