apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-platform
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
